
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.ImageIcon;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sarpr
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    
    private int num;
    
    int getNum()
    {
        return num;
    }
    
    void setNum(int n){
        num=n;
    }
    public HomePage() {
        initComponents();
         fileChooser=new FileChooser(this, rootPaneCheckingEnabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        beforeImagePanel = new javax.swing.JPanel();
        BeforeImage = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Encryption = new javax.swing.JLabel();
        Decryption = new javax.swing.JLabel();
        afterEncodePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        afterEncode = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        next = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setType(java.awt.Window.Type.UTILITY);

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        beforeImagePanel.setForeground(new java.awt.Color(0, 255, 255));
        beforeImagePanel.setOpaque(false);
        beforeImagePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BeforeImage.setBackground(new java.awt.Color(153, 255, 153));
        BeforeImage.setForeground(new java.awt.Color(153, 255, 153));
        BeforeImage.setText("nxdjg");
        BeforeImage.setAutoscrolls(true);
        BeforeImage.setMaximumSize(new java.awt.Dimension(34, 14));
        BeforeImage.setMinimumSize(new java.awt.Dimension(34, 14));
        BeforeImage.setOpaque(true);
        BeforeImage.setPreferredSize(new java.awt.Dimension(34, 14));
        beforeImagePanel.add(BeforeImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 300, 210));
        BeforeImage.getAccessibleContext().setAccessibleName("");

        jLabel3.setBackground(new java.awt.Color(0, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Orignal Image");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel3.setFocusable(false);
        beforeImagePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 230, 30));

        jDesktopPane1.add(beforeImagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 450, 300));

        Encryption.setBackground(new java.awt.Color(0, 255, 255));
        Encryption.setFont(new java.awt.Font("Broadway", 0, 14)); // NOI18N
        Encryption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Encryption.setText("Encode");
        Encryption.setBorder(new javax.swing.border.MatteBorder(null));
        Encryption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Encryption.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Encryption.setOpaque(true);
        Encryption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EncryptionMouseClicked(evt);
            }
        });
        jDesktopPane1.add(Encryption, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 140, 40));

        Decryption.setBackground(new java.awt.Color(0, 255, 255));
        Decryption.setFont(new java.awt.Font("Broadway", 0, 14)); // NOI18N
        Decryption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Decryption.setText("Decode");
        Decryption.setBorder(new javax.swing.border.MatteBorder(null));
        Decryption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Decryption.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Decryption.setOpaque(true);
        Decryption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DecryptionMouseClicked(evt);
            }
        });
        jDesktopPane1.add(Decryption, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 140, 40));

        afterEncodePanel.setOpaque(false);
        afterEncodePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setText("Steganography Image");
        afterEncodePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        afterEncode.setBackground(new java.awt.Color(153, 255, 153));
        afterEncode.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        afterEncode.setOpaque(true);
        afterEncodePanel.add(afterEncode, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 300, 210));

        jDesktopPane1.add(afterEncodePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 450, 300));

        jPanel1.setBackground(new java.awt.Color(6, 83, 78));
        jPanel1.setToolTipText("Enter The Message");
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea2.setBackground(new java.awt.Color(153, 255, 153));
        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 730, 180));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setText("Enter The message Text");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 580, 50));

        next.setBackground(new java.awt.Color(0, 255, 255));
        next.setFont(new java.awt.Font("Broadway", 0, 14)); // NOI18N
        next.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        next.setText("Choose Image");
        next.setBorder(new javax.swing.border.MatteBorder(null));
        next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        next.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        next.setOpaque(true);
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 140, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 240, 40, 40));

        jLabel4.setBackground(new java.awt.Color(0, 255, 255));
        jLabel4.setFont(new java.awt.Font("Broadway", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Choose the bit number to fit the message ");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 330, 40));

        jDesktopPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 770, 310));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/123.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jLabel1.setMinimumSize(new java.awt.Dimension(1000, 1000));
        jDesktopPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EncryptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EncryptionMouseClicked
        // TODO add your handling code here:
  
        jPanel1.setVisible(true);
        jLabel2.setText("Enter The Message Text ");
        jTextArea2.setText("");
        next.setText("Choose Image");
        
        next.setVisible(true);

    }//GEN-LAST:event_EncryptionMouseClicked

    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked
        // TODO add your handling code here:
         if(!next.getText().equals("Submit"))
            {    
                   fileChooser.setVisible(true);
                  
                   try{
                   BufferedImage image;
                   File output = new File(fileChooser.filePath);
                   if(fileChooser.filePath!=null)
                   {
                       image = ImageIO.read(output);
                       ImageIcon imageIcon = new ImageIcon(fitimage(image, BeforeImage.getWidth(), BeforeImage.getHeight()));
                        BeforeImage.setIcon(imageIcon);
                        
                        beforeImagePanel.setVisible(true);
                        
                        String n=jComboBox1.getItemAt(jComboBox1.getSelectedIndex());
                        int num=Integer.valueOf(n);
                        setNum(num);
                        System.out.println(num);
                         next.setText("Submit");
               //   BeforeImage.setIcon(img);
                   }
                   else
                   {
                             JOptionPane.showMessageDialog(this,"Please Select Image");
                   }
                  
                   }
                   catch(Exception e){ //JOptionPane.showMessageDialog(this,"message can't be embeded");
                   }
                  
            }
        else
            {
                  if(fileChooser.filePath!=null){ 
                      System.out.println(fileChooser.filePath);
                  try{
                        BufferedImage image;
                        File input = new File(fileChooser.filePath);
                        image = ImageIO.read(input);
                        String msg=jTextArea2.getText();
                        EmbedMessage emb=new EmbedMessage();
                        String message=emb.embedMessage(image,msg,input,num);
                        if(message !=null)
                        {  
                            JOptionPane.showMessageDialog(this,"Path is "+message);
                            image = ImageIO.read(new File(message));
               
                       ImageIcon imageIcon = new ImageIcon(fitimage(image, BeforeImage.getWidth(), BeforeImage.getHeight()));
                        afterEncode.setIcon(imageIcon);
                        
                        afterEncodePanel.setVisible(true);
                        }
                        
                        
                        jPanel1.setVisible(false);
                     
                     }
                 catch(Exception e){System.out.println(e);
                 // JOptionPane.showMessageDialog(jPanel1,"message can't be embeded");
                 }
       
             } 
       }  

    }//GEN-LAST:event_nextMouseClicked

    private void DecryptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DecryptionMouseClicked
      afterEncode.setIcon(null);
           afterEncodePanel.setVisible(false);
           BeforeImage.setIcon(null);
           beforeImagePanel.setVisible(false);
     fileChooser.setVisible(true);
    if(fileChooser.filePath!=null){
     try{
           jTextArea2.setText("");
           DecodeMessage decode=new DecodeMessage();
           BufferedImage image;
           File output = new File(fileChooser.filePath);
           image = ImageIO.read(output); 
           jPanel1.setVisible(true);
           jLabel2.setText("Decoded Message ");
            String message=decode.decodeMessage(image,num);
           if(message!=null)
           jTextArea2.setText(message);
           next.setVisible(false);
           jPanel1.setVisible(true);
           System.out.println("HomePage.DecryptionMouseClicked()");
         }
        catch(Exception e){System.out.println(e.getMessage());
        JOptionPane.showMessageDialog(this,"Invalid Image !!!");}
        }
          
    }//GEN-LAST:event_DecryptionMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                     UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
              HomePage homePage=  new HomePage();          
              homePage.setBounds(homePage.jLabel1.getX(), homePage.jLabel1.getY(), homePage.jLabel1.getWidth(),homePage.jLabel1.getHeight());
              homePage.jPanel1.setVisible(false);
              homePage.beforeImagePanel.setVisible(false);
              homePage.afterEncodePanel.setVisible(false);
              homePage.setVisible(true);
              homePage.setResizable(false);
 
}
        });
    }
    
    private Image fitimage(Image img , int w , int h)
{
    BufferedImage resizedimage = new BufferedImage(w,h,BufferedImage.TYPE_INT_RGB);
    Graphics2D g2 = resizedimage.createGraphics();
    g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
    g2.drawImage(img, 0, 0,w,h,null);
    g2.dispose();
    return resizedimage;
}

private FileChooser fileChooser;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BeforeImage;
    private javax.swing.JLabel Decryption;
    private javax.swing.JLabel Encryption;
    private javax.swing.JLabel afterEncode;
    private javax.swing.JPanel afterEncodePanel;
    private javax.swing.JPanel beforeImagePanel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel next;
    // End of variables declaration//GEN-END:variables
}



